apiVersion : argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/R-D-Engineering/eks-memos.git
    targetRevision: main
    path: k8s/bootstrap
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      