apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'http://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 77.0.1
    helm:
      values: |
        grafana:
          enabled: true

          admin:
            existingSecret: grafana-admin
            userKey: admin-user
            passwordKey: admin-password

          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.ai-engineering-aph.online
            path: /
            pathType: Prefix
            tls:
              - hosts:
                  - grafana.ai-engineering-aph.online
                secretName: grafana-tls

        prometheus:
          prometheusSpec:
            retention: 7d
  destination:        
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
       - CreateNamespace=true
       - ServerSideApply=true